# Generated by Django 5.0.4 on 2024-04-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_approvisionnementhistorique_utilisateur'),
        ('employe_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantite', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe_panel.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.produit')),
            ],
        ),
    ]
