# Generated by Django 5.0.4 on 2024-04-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
