# Generated by Django 5.0.4 on 2024-04-09 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_approvisionnementhistorique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvisionnementhistorique',
            name='utilisateur',
        ),
    ]
